<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="utf-8">
    <title>Introdução Instrução try...catch...finally</title>
</head>
<body>

    <h2>Introdução a instrução try...catch...finally</h2>

    <p>O fluxograma a seguir ilustra como try...catch...finally funciona:</p>

    <img src="./images/javascript-try-catch-finally.svg" alt="fluxograma">

    <script>

        /**
         * * TRY...CATCH...FINALLY - PEGUE...CAPTURE...FINALIZE
         * 
         * Resumo : neste tutorial, você aprenderá como usar a try...catch...finally instrução JavaScript para capturar exceções e executar um bloco, independentemente de as exceções ocorrerem ou não
         * 
         * * INTRODUÇÃO À INSTRUÇÃO TRY...CATCH...FINALLY DO JS
         * 
         * A try...catch instrução permite capturar exceções e tratá-las normalmente. Às vezes, você deseja executar um bloco independentemente de ocorrerem exceções ou não. Nesse caso, você pode usar a try...catch...finally instrução com a seguinte sintaxe:
        */

        //sintaxe da try...catch...finally instrução
        try{
            //código pode causar erro
        }catch(error) {
            //código para lidar com erro
        }finally{
            //código para executar se as exceções ocorrem ou não
        }

        /**
         * Nesta sintaxe, o finally bloco sempre é executado após os blocos try e catch serem concluídos e ocorrerem exceções ou não.
         * 
         * O fluxograma a seguir ilustra como try...catch...finally funciona:
        */
    </script>

</body>
</html>